using Microsoft.Extensions.Options;

namespace BlogEngine.Server.Storage;

/// <summary>
/// Stores media as plain files under <see cref="MediaStorageOptions.RootPath"/> (design 9.3, Q5).
/// </summary>
/// <remarks>
/// <para>
/// Keys map directly to relative paths. They are generated by the server, but every key is still checked so it
/// can never resolve outside the root (no <c>..</c> segments, rooted paths or backslashes).
/// </para>
/// <para>
/// Writes go to a temporary file in the target folder first and are then moved into place, so a reader never
/// sees a half-written image and a failed upload leaves nothing behind.
/// </para>
/// </remarks>
public sealed class FileSystemMediaStorage : IMediaStorage
{
    private const int BufferSize = 81920;

    private readonly string root;

    /// <summary>Resolves the root folder from the options and the host's content root, creating it if needed.</summary>
    public FileSystemMediaStorage(IOptions<MediaStorageOptions> options, IHostEnvironment environment)
        : this(Path.Combine(environment.ContentRootPath, options.Value.RootPath))
    {
    }

    /// <summary>Uses <paramref name="rootPath"/> as the root folder, creating it if needed.</summary>
    public FileSystemMediaStorage(string rootPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(rootPath);

        root = Path.GetFullPath(rootPath);
        Directory.CreateDirectory(root);
    }

    /// <summary>The absolute root folder.</summary>
    public string RootPath => root;

    /// <inheritdoc />
    public async Task SaveAsync(string key, Stream content, string contentType, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(content);

        var path = ResolvePath(key);
        var directory = Path.GetDirectoryName(path)!;
        Directory.CreateDirectory(directory);

        var tempPath = Path.Combine(directory, $".{Path.GetFileName(path)}.{Guid.NewGuid():N}.tmp");
        try
        {
            await using (var file = new FileStream(tempPath, FileMode.CreateNew, FileAccess.Write, FileShare.None, BufferSize, useAsync: true))
            {
                await content.CopyToAsync(file, ct);
            }

            File.Move(tempPath, path, overwrite: true);
        }
        catch
        {
            TryDeleteFile(tempPath);
            throw;
        }
    }

    /// <inheritdoc />
    public Task<Stream?> OpenReadAsync(string key, CancellationToken ct)
    {
        var path = ResolvePath(key);
        try
        {
            Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read | FileShare.Delete, BufferSize, useAsync: true);
            return Task.FromResult<Stream?>(stream);
        }
        catch (Exception ex) when (ex is FileNotFoundException or DirectoryNotFoundException)
        {
            return Task.FromResult<Stream?>(null);
        }
    }

    /// <inheritdoc />
    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var path = ResolvePath(key);
        if (File.Exists(path))
        {
            File.Delete(path);
            DeleteEmptyParents(Path.GetDirectoryName(path)!);
        }

        return Task.CompletedTask;
    }

    /// <inheritdoc />
    public Task DeletePrefixAsync(string prefix, CancellationToken ct)
    {
        ArgumentException.ThrowIfNullOrEmpty(prefix);

        // A prefix ending in "/" names a folder; otherwise it also matches file and folder names in its parent.
        var isFolder = prefix.EndsWith('/');
        var basePath = ResolvePath(isFolder ? prefix.TrimEnd('/') : prefix);
        if (isFolder)
        {
            if (Directory.Exists(basePath))
            {
                Directory.Delete(basePath, recursive: true);
            }
        }
        else
        {
            var parent = Path.GetDirectoryName(basePath)!;
            var namePrefix = Path.GetFileName(basePath);
            if (Directory.Exists(parent))
            {
                foreach (var entry in Directory.EnumerateFileSystemEntries(parent, namePrefix + "*"))
                {
                    if (Directory.Exists(entry))
                    {
                        Directory.Delete(entry, recursive: true);
                    }
                    else
                    {
                        File.Delete(entry);
                    }
                }
            }
        }

        DeleteEmptyParents(Path.GetDirectoryName(basePath)!);
        return Task.CompletedTask;
    }

    /// <summary>
    /// The absolute path of <paramref name="key"/>, rejecting keys that are empty, rooted, contain backslashes or
    /// <c>.</c>/<c>..</c> segments, or would otherwise resolve outside the root.
    /// </summary>
    /// <exception cref="ArgumentException">The key is not a safe relative key.</exception>
    private string ResolvePath(string key)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(key);

        var segments = key.Split('/');
        if (key.Contains('\\') || Path.IsPathRooted(key) || segments.Any(s => s is "" or "." or ".."))
        {
            throw new ArgumentException($"'{key}' is not a valid media storage key.", nameof(key));
        }

        var path = Path.GetFullPath(Path.Combine([root, .. segments]));
        if (!path.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new ArgumentException($"'{key}' resolves outside the media root.", nameof(key));
        }

        return path;
    }

    /// <summary>Removes folders left empty by a delete, up to (not including) the root.</summary>
    private void DeleteEmptyParents(string directory)
    {
        while (directory.Length > root.Length
            && directory.StartsWith(root, StringComparison.Ordinal)
            && Directory.Exists(directory)
            && !Directory.EnumerateFileSystemEntries(directory).Any())
        {
            Directory.Delete(directory);
            directory = Path.GetDirectoryName(directory)!;
        }
    }

    private static void TryDeleteFile(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
            // Best effort: a leftover temporary file is harmless and ignored by readers.
        }
    }
}