<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlogEngine.Data\BlogEngine.Data.csproj" />
    <ProjectReference Include="..\..\src\BlogEngine.Server\BlogEngine.Server.csproj" />
    <ProjectReference Include="..\BlogEngine.ServiceDefaults\BlogEngine.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
