using BlogEngine.Shared.Common;
using BlogEngine.Shared.Contracts;
using BlogEngine.Shared.Validation;

namespace BlogEngine.UnitTests.Validation;

/// <summary>
/// Tests <see cref="PostEditValidator"/>: the shared post rules used by the editor and the server (T1.1).
/// </summary>
public class PostEditValidatorTests
{
    /// <summary>A minimal post with just a title is valid; slug and summary are generated when blank.</summary>
    [Test]
    public async Task Validate_MinimalPost_IsValid()
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "Hello" });

        await Assert.That(errors).IsEmpty();
    }

    /// <summary>The title is required; whitespace doesn't count.</summary>
    [Test]
    [Arguments("")]
    [Arguments("   ")]
    public async Task Validate_BlankTitle_IsRejected(string title)
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = title });

        await Assert.That(errors.Keys).IsEquivalentTo([nameof(PostEditDto.Title)]);
    }

    /// <summary>Lengths come from <see cref="FieldLengths"/>, one past the limit fails and the limit passes.</summary>
    [Test]
    [Arguments(nameof(PostEditDto.Title), FieldLengths.PostTitle)]
    [Arguments(nameof(PostEditDto.Summary), FieldLengths.PostSummary)]
    [Arguments(nameof(PostEditDto.MetaTitle), FieldLengths.MetaTitle)]
    [Arguments(nameof(PostEditDto.MetaDescription), FieldLengths.MetaDescription)]
    public async Task Validate_EnforcesMaxLengths(string property, int maxLength)
    {
        var atLimit = WithValue(property, new string('a', maxLength));
        var overLimit = WithValue(property, new string('a', maxLength + 1));

        await Assert.That(PostEditValidator.Validate(atLimit)).IsEmpty();
        await Assert.That(PostEditValidator.Validate(overLimit).Keys).IsEquivalentTo([property]);
    }

    /// <summary>Slugs generated by <c>SlugGenerator</c> are accepted, as is a blank slug.</summary>
    [Test]
    [Arguments(null)]
    [Arguments("")]
    [Arguments("hello")]
    [Arguments("hello-world-2")]
    [Arguments("2026-recap")]
    public async Task Validate_WellFormedSlug_IsValid(string? slug)
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "Hello", Slug = slug });

        await Assert.That(errors).IsEmpty();
    }

    /// <summary>Only lowercase <c>[a-z0-9]</c> words separated by single hyphens are allowed.</summary>
    [Test]
    [Arguments("Hello")]
    [Arguments("hello world")]
    [Arguments("hello_world")]
    [Arguments("-hello")]
    [Arguments("hello-")]
    [Arguments("hello--world")]
    [Arguments("café")]
    [Arguments("hello/world")]
    public async Task Validate_MalformedSlug_IsRejected(string slug)
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "Hello", Slug = slug });

        await Assert.That(errors.Keys).IsEquivalentTo([nameof(PostEditDto.Slug)]);
    }

    /// <summary>Slugs longer than the column are rejected even when well formed.</summary>
    [Test]
    public async Task Validate_TooLongSlug_IsRejected()
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "Hello", Slug = new string('a', FieldLengths.Slug + 1) });

        await Assert.That(errors.Keys).IsEquivalentTo([nameof(PostEditDto.Slug)]);
    }

    /// <summary>Tag names follow <c>TagNormalizer</c>: no delimiters, not blank, not too long.</summary>
    [Test]
    [Arguments("a,b")]
    [Arguments("a;b")]
    [Arguments("   ")]
    public async Task Validate_InvalidTag_IsRejected(string tag)
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "Hello", Tags = ["C#", tag] });

        await Assert.That(errors.Keys).IsEquivalentTo([nameof(PostEditDto.Tags)]);
        await Assert.That(errors[nameof(PostEditDto.Tags)]).Count().IsEqualTo(1);
    }

    /// <summary>Duplicates by normalized name count once towards the tag limit.</summary>
    [Test]
    public async Task Validate_TagLimit_CountsDistinctTags()
    {
        var distinct = Enumerable.Range(1, PostEditValidator.MaxTags).Select(i => $"tag{i}").ToList();
        var withDuplicates = new PostEditDto { Title = "Hello", Tags = [.. distinct, "TAG1", " tag2 "] };
        var tooMany = new PostEditDto { Title = "Hello", Tags = [.. distinct, "one-more"] };

        await Assert.That(PostEditValidator.Validate(withDuplicates)).IsEmpty();
        await Assert.That(PostEditValidator.Validate(tooMany).Keys).IsEquivalentTo([nameof(PostEditDto.Tags)]);
    }

    /// <summary>Every failing field is reported at once.</summary>
    [Test]
    public async Task Validate_ReportsEveryInvalidField()
    {
        var errors = PostEditValidator.Validate(new PostEditDto { Title = "", Slug = "Bad Slug", Tags = ["a,b"] });

        await Assert.That(errors.Keys).IsEquivalentTo(
            [nameof(PostEditDto.Title), nameof(PostEditDto.Slug), nameof(PostEditDto.Tags)]);
    }

    private static PostEditDto WithValue(string property, string value)
    {
        var post = new PostEditDto { Title = "Hello" };
        typeof(PostEditDto).GetProperty(property)!.SetValue(post, value);
        return post;
    }
}
